version: '3.2'

services:
  nest-app:
    build:
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    command: npm run start
    volumes:
      # Re-use local composer cache via host-volume
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - saas-energy
    env_file:
      - .env
    depends_on:
      - mongo

  database:
    image: mongo:latest
    container_name: 'mongodb'
    volumes:
      - mongodb_data_container:/data/db
    env_file:
      - .env
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_DATEBASE}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    networks:
      - saas-energy

networks:
  saas-energy:
    driver: bridge
