import {
  ActionEnum,
  AddressType,
  SubjectEnum,
  User,
  UserStatus,
} from '@prisma/client';

export const fakeData: User = {
  id: 'user-id',
  firstname: 'John',
  lastname: 'Doe',
  username: 'johndoe',
  password:
    '$argon2id$v=19$m=65536,t=3,p=4$f+0kBa9fD6cExuwn/+Obug$C8I/ylTXWI7EzgrABXiVclIkJsbDu/jCEJ0LuwzqAzY',
  email: 'john.doe@example.com',
  phone: '1234567890',
  addressType: AddressType.HOME,
  longitude: '',
  latitude: '',
  emailVerified: false,
  location: 'Some Location',
  staffId: 'staff-id',
  roleId: 'role-id',
  status: UserStatus.active,
  isBlocked: false,
  createdAt: new Date(),
  updatedAt: new Date(),
  deletedAt: null,
  lastLogin: new Date(),
};

export const mockUsersResponseData = [
  {
    id: '66e9fe02014ca14746800d33',
    firstname: 'john',
    lastname: 'okor@gmail',
    username: null,
    password: 'wrehiohjorwerw',
    email: 'francisalexander000@gmail.com',
    phone: '09062736182',
    addressType: AddressType.HOME,
    longitude: '',
    latitude: '',
    emailVerified: false,
    location: 'Abuja',
    staffId: null,
    status: UserStatus.active,
    isBlocked: false,
    roleId: '66e9ecc37cadd7f6e4b76e42',
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
    lastLogin: null,
    role: {
      id: '66e9ecc37cadd7f6e4b76e42',
      role: 'admin',
      active: true,
      created_at: new Date(),
      updated_at: new Date(),
      deleted_at: null,
      permissions: [
        {
          id: '66e9ecc37cadd7f6e4b76e43',
          action: ActionEnum.manage,
          subject: SubjectEnum.all,
          roleId: '66e9ecc37cadd7f6e4b76e42',
          created_at: new Date(),
          updated_at: new Date(),
          deleted_at: null,
        },
      ],
    },
  },
];
