name: energy-project-backend 
on:
  # push:
    # branches:
    #   - main
  pull_request:
    branches:
      - main
    types: [closed]
jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
 
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
 
      - name: Install dependencies
        run: npm install
 
      - name: Run build
        run: npm run build
 
      - name: rename env.example to .env
        run: mv .env.example .env
 
      - name: Replace environment variables in .env
        run: |
          sed -i -e "s|DATABASE_URL=forge|DATABASE_URL=$(echo '${{ secrets.DATABASE_URL }}' | sed 's|&|\\&|g')|" .env
          sed -i -e "s|ALLOWED_ORIGIN=.*|DB_PORT=${{ secrets.DB_PORT }}|" .env
          sed -i -e "s|PORT=.*|PORT=${{ secrets.PORT }}|" .env
          sed -i -e "s|APP_NAME=.*|APP_NAME='${{ secrets.APP_NAME }}'|" .env
          sed -i -e "s|CLIENT_URL=.*|CLIENT_URL=${{ secrets.CLIENT_URL }}|" .env
          sed -i -e "s|JWT_SECRET_KEY=.*|JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}|" .env
          sed -i -e "s|EMAIL_USER=.*|EMAIL_USER=${{ secrets.EMAIL_USER }}|" .env
          sed -i -e "s|EMAIL_PWD=.*|EMAIL_PWD='${{ secrets.EMAIL_PWD }}'|" .env
          sed -i -e "s|EMAIL_PORT=.*|EMAIL_PORT=${{ secrets.EMAIL_PORT }}|" .env
          sed -i -e "s|EMAIL_HOST=.*|EMAIL_HOST=${{ secrets.EMAIL_HOST }}|" .env
          sed -i -e "s|MAIL_FROM=.*|MAIL_FROM=${{ secrets.MAIL_FROM }}|" .env
          sed -i -e "s|MONGO_PORT=.*|MONGO_PORT=${{ secrets.MONGO_PORT }}|" .env
          sed -i -e "s|CLOUDINARY_API_KEY=.*|CLOUDINARY_API_KEY='${{ secrets.CLOUDINARY_API_KEY }}'|" .env
          sed -i -e "s|CLOUDINARY_API_SECRET=.*|CLOUDINARY_API_SECRET='${{ secrets.CLOUDINARY_API_SECRET }}'|" .env
          sed -i -e "s|CLOUDINARY_CLOUD_NAME=.*|CLOUDINARY_CLOUD_NAME='${{ secrets.CLOUDINARY_CLOUD_NAME }}'|" .env
          sed -i -e "s|FLW_SECRET_KEY=.*|FLW_SECRET_KEY='${{ secrets.FLW_SECRET_KEY }}'|" .env
          sed -i -e "s|FLW_PUBLIC_KEY=.*|FLW_PUBLIC_KEY='${{ secrets.FLW_PUBLIC_KEY }}'|" .env
          sed -i -e "s|FLW_WEBHOOK_SECRET=.*|FLW_WEBHOOK_SECRET='${{ secrets.FLW_WEBHOOK_SECRET }}'|" .env
          sed -i -e "s|FLW_ENCRYPTION_KEY=.*|FLW_ENCRYPTION_KEY='${{ secrets.FLW_ENCRYPTION_KEY }}'|" .env
          sed -i -e "s|PAYMENT_REDIRECT_URL=.*|PAYMENT_REDIRECT_URL='${{ secrets.PAYMENT_REDIRECT_URL_TEST }}'|" .env
          sed -i -e "s|FRONTEND_SUCCESSFUL_SALES_URL=.*|FRONTEND_SUCCESSFUL_SALES_URL='${{ secrets.FRONTEND_SUCCESSFUL_SALES_URL_TEST }}'|" .env
          sed -i -e "s|COMPANY_LOGO_URL=.*|COMPANY_LOGO_URL='${{ secrets.COMPANY_LOGO_URL_TEST }}'|" .env
          sed -i -e "s|REDIS_URL=.*|APP_NAME='${{ secrets.REDIS_URL }}'|" .env

      - name: Copy Prisma Schema folder
        run: cp -r prisma/schema dist/prisma/schema
 
      - name: Update apt repositories 
        run: sudo apt update
 
      - name: Install rsync
        run: sudo apt-get install -y rsync
 
      
      - name: Install rsync
        run: sudo apt-get install -y rsync
    
      - name: SSH login and deploy
        run: |
          mkdir -p ~/.ssh
          echo "${{secrets.SSH_PRIVATE_KEY}}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          rsync --delete -va -e 'ssh -p 7822 -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no' \
            dist/ package.json .env .htaccess skillz@103.72.76.68:ubuxa/api || exit_code=$?
          if [ "$exit_code" -ne 0 ] && [ "$exit_code" -ne 24 ]; then
            exit $exit_code
          fi
 
      # - name: SSH login and deploy
      #   run: |
      #     mkdir -p ~/.ssh
      #     echo "${{secrets.SSH_PRIVATE_KEY}}" > ~/.ssh/id_rsa
      #     chmod 600 ~/.ssh/id_rsa
      #     rsync --delete -va -e 'ssh -p 7822 -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no' \
      #       dist/ package.json  .env .htaccess skillz@103.72.76.68:ubuxa/api
      - name: SSH and effect migration
        run: |
          ssh -p 7822 -i ~/.ssh/id_rsa -t skillz@103.72.76.68 "
            cd ubuxa/api && \
            npm install && \
            npx prisma generate && \
            npx prisma db push && \
            cloudlinux-selector stop --json --interpreter nodejs --app-root ubuxa/api && \
            cloudlinux-selector start --json --interpreter nodejs --app-root ubuxa/api
          "